# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-15 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreBoardAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Time',
            field=models.IntegerField(),
        ),
    ]
